# Generated by Django 4.2.7 on 2023-12-19 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_book_options_userbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='books', through='tracker.UserBook', to=settings.AUTH_USER_MODEL),
        )
    ]
