# Generated by Django 4.2.7 on 2024-02-14 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveIntegerField()),
                ('read_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InProgressRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveIntegerField()),
                ('read_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('current_page', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('page_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeriesBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_in_series', models.PositiveIntegerField()),
                ('full_series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.series')),
            ],
        ),
        migrations.CreateModel(
            name='ToReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': [django.db.models.functions.text.Lower('title')]},
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Author', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Title', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
        migrations.AddField(
            model_name='toreadbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.book'),
        ),
        migrations.AddField(
            model_name='toreadbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inprogressread',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.book'),
        ),
        migrations.AddField(
            model_name='inprogressread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedread',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.book'),
        ),
        migrations.AddField(
            model_name='finishedread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.seriesbook'),
        ),
        migrations.AlterUniqueTogether(
            name='inprogressread',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='finishedread',
            unique_together={('user', 'book')},
        ),
    ]
