# Generated by Django 5.0.2 on 2024-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_series_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toreadbook',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
